server:
  port: 8098
  
spring:
  application:
    name: studentservice  
  data:
    mongodb:  
      # uri: mongodb+srv://admin:admin@cluster0-hsyh0.gcp.mongodb.net/?ssl=true&replicaSet=cluster0-hsyh0-0&authSource=admin
       uri: mongodb://localhost:27017      
       database: studentservice 
  #activemq:
   # broker-url: tcp://localhost:61616
   # user: admin
   # password: admin
    
    
logging:
    level:     
      com.studentservice: INFO
    pattern:
     console: "%d{yyyy-MM-dd HH:mm:ss} %-5level  - %msg%n"
     file:    "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: /logs/studentservice.log
  
